# Generated by Django 5.1.4 on 2025-01-08 14:33

import control_combustible.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=6)),
                ('capacidad', models.IntegerField()),
                ('contenido', models.IntegerField()),
                ('vencimiento_filtro', models.DateField()),
                ('vencimiento_certificacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Despachador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('privilegios', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ModeloHelicoptero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_modelo', models.CharField(max_length=10)),
                ('capacidad_modelo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Receptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ValeCombustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('litros_cargados', models.IntegerField()),
                ('matricula_aeronave', models.CharField(max_length=10, verbose_name=control_combustible.models.Aeronave)),
                ('patente_camion', models.CharField(max_length=6, verbose_name=control_combustible.models.Camion)),
                ('motivo', models.CharField(max_length=100)),
                ('despachador', models.CharField(max_length=100, verbose_name=control_combustible.models.Despachador)),
                ('receptor', models.CharField(max_length=100, verbose_name=control_combustible.models.Receptor)),
            ],
        ),
        migrations.CreateModel(
            name='Aeronave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=6)),
                ('capacidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacidad_helicoptero', to='control_combustible.modelohelicoptero')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelo_helicoptero', to='control_combustible.modelohelicoptero')),
            ],
        ),
    ]
