# Generated by Django 5.1.4 on 2025-01-09 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=6)),
                ('capacidad', models.IntegerField()),
                ('contenido', models.IntegerField()),
                ('vencimiento_filtro', models.DateField()),
                ('vencimiento_certificacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ModeloHelicoptero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_modelo', models.CharField(max_length=10)),
                ('capacidad_modelo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Aeronave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidad', models.IntegerField()),
                ('matricula', models.CharField(max_length=6)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelo', to='control_combustible.modelohelicoptero')),
            ],
        ),
        migrations.CreateModel(
            name='ValeCombustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_vale', models.IntegerField(default=0)),
                ('fecha', models.DateField()),
                ('litros_cargados', models.IntegerField()),
                ('motivo', models.CharField(max_length=100)),
                ('despachador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despachador', to='control_combustible.usuario')),
                ('matricula_aeronave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_combustible.aeronave')),
                ('patente_camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_combustible.camion')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptor', to='control_combustible.usuario')),
            ],
        ),
    ]
