# Generated by Django 5.1.4 on 2025-01-06 15:50

import control_combustible.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aeronave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50)),
                ('capacidad', models.IntegerField()),
                ('matricula', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='camion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=6)),
                ('capacidad', models.IntegerField()),
                ('contenido', models.IntegerField()),
                ('vencimiento_filtro', models.DateField()),
                ('vencimiento_certificacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='despachador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('privilegios', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='estanque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_estanque', models.IntegerField()),
                ('capacidad', models.IntegerField()),
                ('contenido', models.IntegerField()),
                ('vencimiento_filtro', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='receptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='tambor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidad', models.IntegerField()),
                ('contenido', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ValeCombustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('litros_cargados', models.IntegerField()),
                ('matricula_aeronave', models.CharField(max_length=10, verbose_name=control_combustible.models.aeronave)),
                ('patente_camion', models.CharField(max_length=6, verbose_name=control_combustible.models.camion)),
                ('motivo', models.CharField(max_length=100)),
                ('despachador', models.CharField(max_length=100, verbose_name=control_combustible.models.despachador)),
                ('receptor', models.CharField(max_length=100, verbose_name=control_combustible.models.receptor)),
            ],
        ),
    ]
