# Generated by Django 5.1.4 on 2025-01-08 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_combustible', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aeronave',
            name='capacidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='aeronave',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelo', to='control_combustible.modelohelicoptero'),
        ),
    ]
