# Generated by Django 5.1.4 on 2025-01-09 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_combustible', '0003_valecombustible_numero_vale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valecombustible',
            name='despachador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_combustible.despachador'),
        ),
        migrations.AlterField(
            model_name='valecombustible',
            name='matricula_aeronave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_combustible.aeronave'),
        ),
        migrations.AlterField(
            model_name='valecombustible',
            name='patente_camion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_combustible.camion'),
        ),
        migrations.AlterField(
            model_name='valecombustible',
            name='receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_combustible.receptor'),
        ),
    ]
